### ISSUE TITLE
searchField for nested objects

### ISSUE THREAD

**Issue by Morena96** [julienlebren/elastic_app_search#3]
how i can add nested object's some field in searchField with type String?

**Comment by julienlebren** [comment]
Please provide a bit of code so I can understand better your question, because I don't understand on which side is the nested object?

**Comment by Morena96** [comment]
indexed inside elastic cloud like:
```
{
      "category":"electronics",
      "name":{
         "en":"phone",
         "tk":"telefon"
      }
}
```

i can search category easily by searchField('category').resultFields('name').get(), but how about searching nested field? for example "name__tk"

**Comment by julienlebren** [comment]
You can simply do `searchField('name__tk')`
