### ISSUE TITLE
Print statements in package

### ISSUE THREAD

**Issue by XenLabsNikhil** [julienlebren/elastic_app_search#5]
This package is great for using elastic app search. 

Noticed that there are print statements in the package (v 0.3.0) code which are not controlled from app using this package. 

Two ways to solve it - 
1. Remove print statements
2. Make it configurable from app while defining elastic service or while querying.

Files with print statements - 

`lib/src/service.dart` 
`lib/src/result.dart`

**Comment by julienlebren** [comment]
Yes, that's some code remaining after debug phase, I will remove it.
The 0.4.0 is almost ready, it will remove these print statements.

**Comment by XenLabsNikhil** [comment]
Great. Waiting for version 0.4.0

**Comment by XenLabsNikhil** [comment]
@julienlebren When will version 0.4.0 be available on pub.dev?
